### ISSUE TITLE
在theme主题文件夹中执行npm install后，无法运行hexo s命令

### ISSUE THREAD

**Issue by ititchuan** [zjZSTU/hexo-guide#6]
进到主题文件夹后，比如在next文件夹中，运行了npm install 安装了插件，但是运行hexo s命令就无法启动了，删除了node_modules文件夹后才行，这是什么原因，这个gulp只能安装在hexo根目录下吗？不能在主题文件夹中安装吗？为什么next主题的文件夹中会有package.json,它是怎么执行的呢？

**Comment by zjZSTU** [comment]
问题很多哈，有点没看懂
第一个：在next主题下安装插件后无法启动，在next主题需要安装啥插件，运行hexo s命令是在哪个目录下运行的：工程目录还是主题目录？
第二个：我看了next主题下也有gulpfile.coffee，gulp安装不一定只能在工程根目录下，不过gulp命令运行和gulpfile路径应该配置，同时我的gulpfile里面指定了对public文件夹进行压缩
第三个：next主题包就是一个nodejs工程，而且我们需要在工程_config.yml中配置theme: next，我估计是通过package.json来引入next主题的（这里涉及nodejs开发，我没有操作过）

**Comment by ititchuan** [comment]
npm install命令是在next主题文件夹中运行，hexo s是在hexo init那个网站根目录下运行。

**Comment by ititchuan** [comment]
并不是说hexo网站的根目录下就没有npm install。而是网站根目录下和主题文件夹下，同时都存在了node_modules文件夹。现在我要想运行主题文件夹下的gulpfile文件，不能从主题文件夹里面运行，而要在hexo根目录下先把主题文件夹中package.json，中的依赖包一个一个的在根目录下手动安装，然后在根目录下运行gulp时指定gulpfile文件路径为  ./theme/next/gulpfile.js

**Comment by ititchuan** [comment]
如果还是不明白我说的啥，你cd theme/next,然后npm install，然后返回根目录，运行hexo s，应该就能看到运行不起来了。

**Comment by zjZSTU** [comment]
懂你意思了，你想要运行主题路径下的gulp file，但是在工程路径下安装相关依赖包

我试了一下，没有问题，操作如下：

1. 先把工程路径下和主题路径下的node_modules全部删除
2. 进入主题路径
3. 运行npm install
4. 运行gulp，可以运行
5. 回退到工程路径
6. 运行npm install
7. 运行hexo server，正常

**Comment by ititchuan** [comment]
好吧，我的还是不行
![error](https://user-images.githubusercontent.com/14054904/58799149-0d8a4700-8637-11e9-8144-685a027074c0.png)

谢谢回复，我放弃了，还是老老实实在工程路径下写gulp,安装gulp吧。

**Comment by zjZSTU** [comment]
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

你的问题是JS堆内存不足

在网上搜了一下：[Vue-cli搭建的项目出现内存溢出（JavaScript heap out of memory）错误？别慌！](https://zhuweisheng.com.cn/framework/vue-cli-leap-out/)

你再找找相关链接试试

**Comment by ititchuan** [comment]
嗯嗯，我觉得可能是hexo在处理主题文件夹的时候，将node_modules也读到内存中处理了，所以造成了JS堆内存不足，如果可以让hexo忽略掉不必要的文件和文件夹就好了。我再试试。谢谢
